version: "3.8"
services:
    nginx:
        image: shahin1290/boilerplate-nginx:latest
        restart: always
        depends_on:
            - client
            - api
        ports:
            - "80:80"

    client:
        image: shahin1290/boilerplate-client:latest
        environment:
            - CHOKIDAR_USEPOLLING=true

    api:
        image: shahin1290/boilerplate-server:latest
        environment:
            - CLIENT_URL=${CLIENT_URL}
            - BASE_DOMAIN=${BASE_DOMAIN}
            - MONGODB_URL=${MONGODB_URL}
            - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
            - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}