version: "3.8"
services:
  nginx:
    image: shahin1290/boilerplate-nginx:latest
    restart: always
    depends_on:
      - client
      - api
    ports:
      - "80:80"

  client:
    image: shahin1290/boilerplate-client:latest
    environment:
      - CHOKIDAR_USEPOLLING=true

  api:
    image: shahin1290/boilerplate-server:latest
    env_file:
      - ./server/.env
